version: "3.9"


services:
  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    restart: always

#   web:
#     build: .
#     command: >
#       sh -c "python manage.py migrate &&
#              python manage.py collectstatic --noinput &&
#              gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       DB_USER: ${DB_NAME}
#       DB_PASSWORD: ${DB_NAME}
#       DB_NAME: ${DB_NAME}
#       DB_HOST: ${DB_HOST}
#       DB_PORT: ${DB_PORT}
#       EMAIL_HOST_USER: ${EMAIL_HOST_USER}
#       EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
#       DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
#       SECRET_KEY: ${SECRET_KEY}
#       DEBUG: ${DEBUG}
#       DJANGO_SETTINGS_MODULE: mysite.settings
#     restart: always

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./staticfiles:/var/www/static
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - web
#     restart: always

volumes:
  db_data: